### ISSUE TITLE
AttributeError: 'Residue' object has no attribute 'select_atoms'

### ISSUE THREAD

**Issue by dimitrismintis** [richardjgowers/persistence_length_tutorial#1]
Hi,
I deeply appreciate your work and contribution on MDAnalysis project!!
While trying to follow step by step this tutorial, I was stacked on the step when you create an AtomGroup. It is worth pointing that am using anaconda3/lib/python3.6.
so after rewriting the below command
ag = [r.select_atoms("type C or type N") for r in u.residues]
I received the following error:
AttributeError: 'Residue' object has no attribute 'select_atoms'
Many thanks
Dim

**Comment by richardjgowers** [comment]
Hi @dimitrismintis 

I've updated the tutorial for newer version of MDAnalysis & Python, it should work for you now

**Comment by dimitrismintis** [comment]
really appreciate your prompt reply it woks perfectly fine!

**Comment by dimitrismintis** [comment]
If you could also add a line in the tutorial to explain how to iterate through frames and then save the data for persistence length per frame in a txt file will be super!! Many thanks again

**Comment by dimitrismintis** [comment]
it would be tremendous helpful if you can also add a line in the tutorial describing how to iterate over frames/trajectory and then save the output in .dat file. Many many thanks

**Comment by richardjgowers** [comment]
@dimitrismintis this isn't really something the class does normally, you'd usually average across all frames as you wouldn't expect the persistence length to change.  This is what the class is doing by default.

 If you did want to get a time dependent description you'd have to do something like:

```python
with open('output.dat', 'w') as out:
    for i in range(len(u.trajectory)):
        p = PersistenceLength(ags, start=i, stop=i+1)
        p.run()
        p.perform_fit()
        out.write('frame {} lp {}'.format(i, p.lp))


```

**Comment by dimitrismintis** [comment]
many thanks!!!
